### ISSUE TITLE
On-prem install not working.

### ISSUE THREAD

**Issue by whitingjr** [3scale/perftest-toolkit#17]
Hi, Using 3.10 ocp I cannot get 3scale installed and working. Has this toolkit ever been tested in a on-premise cloud installation ?

**Comment by whitingjr** [comment]
By the way, using the flag `--host-pv-dir` is not compatible with OCP 3.10.

```
oc cluster up --host-pv-dir=/mnt/ocp-local-storage/fioa1
Error: unknown flag: --host-pv-dir
```

**Comment by eguzki** [comment]
I am afraid, this has nothing to do with perftest-toolkit. Maybe the issue belongs to https://github.com/3scale/3scale-amp-openshift-templates ??

@whitingjr If you agree, please close this issue

**Comment by whitingjr** [comment]
I agree.
