### ISSUE TITLE
Problem running the injector

### ISSUE THREAD

**Issue by adeeyacoby10** [3scale/perftest-toolkit#33]
Hi,
I am trying to run the injector playbook and in the task of -
injector-configurator : Run Buddhi to create traffic file 
I get the following error:
fatal: [injector]: FAILED! => {"changed": false, "msg": "\u001b[1m\u001b[31mErrno::EACCES: Permission denied @ rb_sysopen - /traffic/traffic.csv\u001b[0m\r\n", "status": 1}

I attached as well a picture of the error
![Annotation 2020-03-24 115640](https://user-images.githubusercontent.com/48152196/77412475-9b9e0c80-6dc6-11ea-9e1c-7fc70c75ff55.png)

Thanks a lot,
Adee Yacoby

**Comment by eguzki** [comment]
Hi,

That task is just running docker container, mounting local volume and trying to write in the local volume. There issue is that host does not allow to the docker container to write in the mounted volume. Check SElinux configuration in the local host, as it can be the one denying access to the local volume.

Please provide version of the playbook you are running. At least, commit id.

**Comment by adeeyacoby10** [comment]
HI,
The issue was with the SElinux.
Thanks for the help,
Adee
